language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
os:
- linux
- osx
addons:
  apt:
    packages:
      - libdb-dev
before_install:
- echo $LANG
- echo $LC_ALL
notifications:
  irc:
    channels:
      - "irc.irccloud.com#builds"
    nick: travisci
    password: Mangrove
  email:
    - bob@rud.is
